from flask import Flask

app = Flask(__name__)

@app.route("/")
def index():
    return "<br />".join([
        "Index Of FlagService /",
        "---------------------",
        "/flags",
        "---------------------",
        "Generated by SuperSecure Python 1.0",
    ])
    


@app.route("/flags")
def indexf():
    return "<br />".join([
        "Index Of FlagService /flags",
        "---------------------",
        "/i-want-it-all",
        "---------------------",
        "Generated by SuperSecure Python 1.0",
    ])    

@app.route("/flags/i-want-it-all")
def indexfi():
    return "<br />".join([
        "Index Of FlagService /flags",
        "---------------------",
        "D0NotTellMeYouV3FoundMe",
        "---------------------",
        "Generated by SuperSecure Python 1.0",
    ])


@app.route("/flags/i-want-it-all/D0NotTellMeYouV3FoundMe")
def indexfig():
    return "Yes you did. The flag is ManuChaoBobbyMarley"