


version: '3'
services:
  jira-sprint:
    # image: amouat/revealjs
    # image: rhuss/docker-reveal
    build:
      context: from-jira-sprint/.docker
      target: slides
    ports:
      - "8000:8000"
    volumes:
      - ./from-jira-sprint/slides/index.html:/reveal.js/index.html:ro
      - ./from-jira-sprint/slides/current/slides.md:/reveal.js/slides.md:ro

      