version: "3.8"

services:
  python-fastapi:
    build:
      context: ./python
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - PYTHONUNBUFFERED=1
      - LOGLEVEL=DEBUG
    volumes:
      - ./python:/app
    ports:
      - 8080:8080
    
  nodejs-express:
    build:
      context: ./nodejs
      dockerfile: Dockerfile
      target: express
    volumes:
      - ./nodejs:/app
    ports:
      - 8081:8081
  
  nodejs-hapi:
    build:
      context: ./nodejs
      dockerfile: Dockerfile
      target: hapi
    volumes:
      - ./nodejs:/app
    ports:
      - 8082:8082